theme: "hugo-book"

languageCode: "en-us"

baseURL: "https://misura.diantonioandrea.com/"
title: "misura"

googleAnalytics: ""
disablePathToLower: true
enableGitInfo: true
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

menu:
  after:
    - name: "GitHub"
      url: "https://github.com/diantonioandrea/misura"
      weight: 1

params:
  BookTheme: auto
  BookToC: true
  BookSection: docs
  BookRepo: 'https://github.com/diantonioandrea/misuraDocs'
  BookDateFormat: 'Monday, January 2, 2006'
  BookSearch: true
  BookComments: false
  BookPortableLinks: true
