theme: "hugo-book"

languageCode: "en-us"

baseURL: "https://misura.diantonioandrea.com/"
title: "misura"

googleAnalytics: ""
disablePathToLower: true
enableGitInfo: false
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

languages:
  en:
    languageName: English
    contentDir: content.en
    weight: 1

params:
  BookTheme: auto
  BookToC: true
  # BookMenuBundle: /menu
  BookSection: docs
  BookRepo: 'https://github.com/diantonioandrea/misuraDocs'
  BookDateFormat: 'January 2, 2006'
  BookSearch: true
  BookComments: false
  BookPortableLinks: true
  BookServiceWorker: true
