name: Fetch Currencies Rates

# Runs everyday at 12:00 UTC.
on:
  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Removes the old version of rates.json.
      - name: Remove Old Rates and Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rm content/currencies/rates.json
          git add -A
          git commit -m "Removed old rates"
      
      # Fetch the new rates.
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with:
          endpoint: ${{ format('{0}{1}', 'http://data.fixer.io/api/latest?access_key=', secrets.API_KEY) }}
          configuration: '{ "method": "GET" }'
          save-location: 'content/currencies'
          save-name: 'rates'
      
      # Commit changes to the repository.
      - name: Commit Changes
        run: |
          git add -A
          git commit -m "Updated rates"
        
      # Push every change made.
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
